language: node_js
node_js:
    - "8"

deploy:
    provider: script
    script: "npm test"
    skip_cleanup: true

services:
    - postgresql

before_script:
    - cp config.yml.travis config.yml
    - psql -c 'create database shared-server-travis;' -U postgres
