language: node_js
node_js:
    - "8"

deploy:
    provider: script
    script: "npm test"
    skip_cleanup: true

notifications:
    email:
        recipients:
            - damiancassinotti@gmail.com
        on_success: always
        on_failure: always
