dist: xenial
language: node_js
node_js:
    - "8"
sudo: true

services:
    - postgresql
addons:
  postgresql: "10"

deploy:
  provider: script
  script: "npm test"
  skip_cleanup: true

before_script:
    - cp config.json.travis config.json
    - psql -c 'create database shared_server_travis;' -U postgres
    - psql -U postgres -d shared_server_travis -a -f db/scripts/tracking.sql
    - psql -U postgres -d shared_server_travis -a -f db/scripts/payments.sql
    - psql -U postgres -d shared_server_travis -a -f db/scripts/servers.sql
    - psql -U postgres -d shared_server_travis -a -f db/scripts/login.sql
    - psql -U postgres -d shared_server_travis -a -f db/scripts/requests.sql
