swagger: '2.0'
info:
  description: API para el shared server de Comprame
  title: Comprame - Shared Server API
  version: 1.0.0
host: shared-server-tallerii.herokuapp.com
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: tracking
    description: |
      Llamados relacionados con la administracion del seguimiento de los envios
  - name: payment
    description: |
      Llamados relacionados con la administración de los pagos
paths:
  /tracking:
    get:
      tags:
      - "tracking"
      summary: "Obtiene el listado de envios. Cada envio viene en su estado actual."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        201:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Tracking"
        500:
          description: "Unexpected error. Code 0"
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
      - "tracking"
      summary: "Crea un nuevo envio para su seguimiento"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        201:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Tracking"
        500:
          description: "Unexpected error. Code 0"
          schema:
            $ref: "#/definitions/Error"
  /tracking/{trackingId}:
    parameters:
      - description: "Identificador del envío"
        in: path
        name: trackingId
        required: true
        type: string
    get:
      tags:
        - tracking
      description: "Devuelve toda la información del viaje. Por cada modificacion que tenga dicho envio se devolvera un objeto tracking."
      responses:
        200:
          description: "Información del envío"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Tracking"
        404:
          description: "Viaje inexistente. Code 1"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Unexpected error. Code 0"
          schema:
            $ref: "#/definitions/Error"
      summary: "Obtener información de un viaje"
    put:
      tags:
        - tracking
      description: "Devuelve la informacion actualizada del envio."
      parameters:
        - description: Nuevo estado del envio
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/NewTrackingStatus"
      responses:
        200:
          description: "Información del envío"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Tracking"
        400:
          description: "Parametros faltantes. Code 1"
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Viaje inexistente. Code 2"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Unexpected error. Code 0"
          schema:
            $ref: "#/definitions/Error"
      summary: "Obtener información de un viaje"
  /payments:
    get:
      tags:
      - "payment"
      summary: "Get my payments"
      operationId: "getPayments"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PaymentResponse"
        500:
          description: "Unexpected error. Code 0"
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
      - "payment"
      summary: "Create a new payment"
      description: ""
      operationId: "addPayment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Payment's information"
        required: true
        schema:
          $ref: "#/definitions/PaymentRequest"
      responses:
        201:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PaymentResponse"
        500:
          description: "Unexpected error. Code 0"
          schema:
            $ref: "#/definitions/Error"
        400:
          description: "Parametros erroneos. Code 1"
          schema:
            $ref: "#/definitions/Error"
  /payments/methods:
    get:
      tags:
      - "payment"
      summary: "Get available payment methods"
      description: "Returns all the payment methods availables"
      operationId: "getPaymethods"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Paymethod"
        500:
          description: "Unexpected error. Code 0"
          schema:
            $ref: "#/definitions/Error"
  /payments/id/{paymentId}:
    parameters:
      - description: "Identificador del pago"
        in: path
        name: paymentId
        required: true
        type: string
    get:
      tags:
        - payment
      description: "Devuelve toda la información del pago."
      responses:
        200:
          description: "Información del pago"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/PaymentResponse'
        404:
          description: "Pago inexistente. Code 1"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Unexpected error. Code 0"
          schema:
            $ref: "#/definitions/Error"
      summary: "Obtener información de un viaje"
definitions:
  Timestamp:
    type: number
    description: |
      Tiempo en epoch
  Error:
    properties:
      code:
        format: int32
        type: integer
      message:
        type: string
    type: object
  Tracking:
    properties:
      id:
        description: identificador del envío
        type: string
      status:
        $ref: '#/definitions/TrackingStatus'
      updateAt:
        $ref: '#/definitions/Timestamp'
  TrackingStatus:
    type: string
    description: Estados de tracking (PENDIENTE, EN_TRANSITO, ENTREGADO, CANCELADO)
  NewTrackingStatus:
    type: object
    properties:
      status:
        $ref: '#/definitions/TrackingStatus'
    description: Nuevo estado de tracking
  Paymethod:
    type: "object"
    properties:
      id:
        type: "number"
      description:
        type: "string"
  Payment_Paymethod:
    type: "object"
    properties:
      epiration_month:
        type: "string"
      expiration_year:
        type: "string"
      method:
        type: "string"
      number:
        type: "string"
  PaymentRequest:
    type: "object"
    properties:
      transaction_id:
        type: "string"
      currency:
        type: "string"
      value:
        type: "number"
        format: "float"
      paymentMethod:
        $ref:  "#/definitions/Payment_Paymethod"
  PaymentResponse:
    type: "object"
    properties:
      transaction_id:
        type: "string"
      currency:
        type: "string"
      value:
        type: "number"
        format: "float"
      paymentMethod:
        $ref:  "#/definitions/Payment_Paymethod"
      status:
        $ref:  "#/definitions/PaymentStatus"
  PaymentStatus:
    type: string
    description: Estados de Payment (PENDIENTE, CONFIRMADO, CANCELADO)
